name: Jira Dashborad Update

on: workflow_dispatch

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Run the app
        run: java -cp java Main